### ISSUE TITLE
Which maven package reference is correct?

### ISSUE THREAD

**Issue by highel** [3sidedcube/Android-GeoGson#2]
Currently the library is available in maven as 'com.3sidedcube.util:GeoGson:1.5' (Note  The Case). Android Studio can't resolve 'com.3sidedcube.util:geogson:1.5' with gradle.

**Comment by scruffyfox** [comment]
It might be case sensitive, [here's a link](http://search.maven.org/#artifactdetails%7Ccom.3sidedcube.util%7CGeoGson%7C1.5%7Cjar) to the artifact on Maven

**Comment by highel** [comment]
Yeah, but the main page link directs to wrong link.
